# Generated by Django 2.0.6 on 2018-06-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookflod', '0002_auto_20180619_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='langugaes',
            new_name='languages',
        ),
    ]
